ALTER TABLE wcf1_visitor ADD languageID INT(10) NOT NULL DEFAULT 1;
ALTER TABLE wcf1_visitor ADD pageID INT(10) NOT NULL DEFAULT 0;
ALTER TABLE wcf1_visitor ADD pageObjectID INT(10) NOT NULL DEFAULT 0;
