ALTER TABLE wcf1_visitor ADD languageID INT(10) DEFAULT NULL;
ALTER TABLE wcf1_visitor ADD pageID INT(10) DEFAULT NULL;
ALTER TABLE wcf1_visitor ADD pageObjectID INT(10) DEFAULT NULL;

ALTER TABLE wcf1_visitor ADD FOREIGN KEY (languageID) REFERENCES wcf1_language (languageID) ON DELETE SET NULL;
ALTER TABLE wcf1_visitor ADD FOREIGN KEY (pageID) REFERENCES wcf1_page (pageID) ON DELETE SET NULL;
