name: build package
on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: WoltLab Suite Package Creation
        uses: KittMedia/action-wsc-package-create@main
      # Create release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.tar.gz
          name: Release ${{ github.ref_name }}
